from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime

from lego_agent.assistants.openai_assistant import OpenAIAssistant
from lego_agent.core.models import (
    Assistant,
    Project,
    ProjectError,
    ProjectRunResult,
    ProjectStatus,
    Staff,
    Task,
    utc_now,
)
from lego_agent.core.registry import Registry, import_path
from lego_agent.modules.common import capabilities, register_defaults, responsibilities
from lego_agent.project.config import AssistantConfig, ProjectRuntimeConfig, StaffProfileConfig
from lego_agent.project.orchestrator import ProjectManagerOnlyOrchestrator
from lego_agent.workflow.staff_workflow import SinglePassStaffWorkflow

AssistantFactory = Callable[[dict[str, object]], Assistant]

assistant_factories = Registry[AssistantFactory]("assistant_factories")


def register_builtin_factories() -> None:
    """Register assistant implementations shipped by the framework.

    The registry keeps runtime construction configurable: config files refer to
    assistant type names, while the runtime resolves those names into Python
    objects here.
    """
    if assistant_factories.maybe_get("openai") is None:
        assistant_factories.register("openai", lambda options: OpenAIAssistant(**options))


class ProjectRuntime:
    """High-level entry point for running a project goal.

    Think of this class as the application service. It loads extension modules,
    creates the project aggregate, chooses the orchestrator, and returns a
    `ProjectRunResult` that the CLI or a future API can print directly.
    """

    def __init__(
        self,
        config: ProjectRuntimeConfig,
        workflow: SinglePassStaffWorkflow | None = None,
    ) -> None:
        register_defaults()
        register_builtin_factories()
        _load_modules(config.modules)
        self.config = config
        self.workflow = workflow or SinglePassStaffWorkflow()
        self.orchestrator = self._create_orchestrator(config.orchestration.strategy)

    def run(self, goal: str) -> ProjectRunResult:
        """Run one project goal from start to finish.

        Version 1 never raises framework errors to the CLI. Unexpected failures
        are converted into a failed `ProjectRunResult`, which makes command-line
        and API callers easier to handle.
        """
        started_at = utc_now()
        try:
            project = self.create_project(goal)
            result = self.orchestrator.run(project)
            result.started_at = started_at
            result.completed_at = result.completed_at or utc_now()
            result.duration_ms = _duration_ms(started_at, result.completed_at)
            return result
        except Exception as exc:
            completed_at = utc_now()
            return ProjectRunResult(
                project_id="",
                project_goal=goal,
                status=ProjectStatus.FAILED,
                manager_id="",
                manager_name="",
                error=ProjectError(type=exc.__class__.__name__, message=str(exc)),
                started_at=started_at,
                completed_at=completed_at,
                duration_ms=_duration_ms(started_at, completed_at),
            )

    def create_project(self, goal: str) -> Project:
        """Create the first project shape: one project and one manager task.

        The project manager is created from the configured staff profile. The
        project id is generated by `Project`, so the manager is first built with
        a temporary project id and then patched after the project exists.
        """
        manager_profile_name = self.config.project.default_manager_profile
        try:
            manager_profile = self.config.staff_profiles[manager_profile_name]
        except KeyError as exc:
            raise ValueError(f"manager profile '{manager_profile_name}' is not configured") from exc

        project_id = ""
        manager = self._create_staff(manager_profile, project_id=project_id)
        project = Project(
            goal=goal,
            manager_id=manager.id,
            staff={manager.id: manager},
        )
        manager.project_id = project.id
        task = Task(
            project_id=project.id,
            title="Project manager planning task",
            goal=(
                "Analyze the project goal, define assumptions and risks, create a "
                "staffing plan, break down work, propose an execution plan, and "
                "produce an initial project result."
            ),
            assigned_to=manager.id,
            created_by="system",
        )
        project.tasks[task.id] = task
        return project

    def _create_staff(self, profile: StaffProfileConfig, project_id: str) -> Staff:
        """Build a Staff instance from a reusable profile."""
        assistant = _create_assistant(profile.assistant)
        return Staff(
            id=profile.role,
            project_id=project_id,
            name=profile.name,
            role=profile.role,
            title=profile.title,
            description=profile.description,
            responsibilities=[responsibilities.get(name) for name in profile.responsibilities],
            capabilities=[capabilities.get(name) for name in profile.capabilities],
            assistant=assistant,
        )

    def _create_orchestrator(self, strategy: str) -> ProjectManagerOnlyOrchestrator:
        """Resolve orchestration strategy names from config.

        Only `project_manager_only` is intentionally supported in Version 1.
        More strategies should be added here or through a registry later.
        """
        if strategy != "project_manager_only":
            raise ValueError(f"unsupported orchestration strategy: {strategy}")
        return ProjectManagerOnlyOrchestrator(self.workflow)


def _create_assistant(config: AssistantConfig) -> Assistant:
    """Create an assistant from config using the assistant registry."""
    factory = assistant_factories.get(config.type)
    return factory(config.to_assistant_kwargs())


def _load_modules(paths: list[str]) -> None:
    """Import optional modules so they can register framework extensions."""
    for path in paths:
        loaded = import_path(path)
        if callable(loaded):
            loaded()


def _duration_ms(started_at: datetime, completed_at: datetime) -> int:
    return int((completed_at - started_at).total_seconds() * 1000)


def create_project_runtime(config: ProjectRuntimeConfig) -> ProjectRuntime:
    return ProjectRuntime(config)
